service_portal/feedback/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.feedback_list, name="feedback_list"),
    path("new/", views.feedback_new_post, name="feedback_new_post"),
    path("<int:pk>/", views.FeedbackDetailView.as_view(), name="feedback_detail"),
]

service_portal/service_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("feedback/", include("feedback.urls"), name="feedback"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_portal/feedback/models.py
from django.db import models


class RequestType(models.TextChoices):
    WISH = "wish", "Пожелание"
    ISSUE = "issue", "Проблема"
    CLAIM = "claim", "Претензия"
    OTHER = "other", "Другое"


class Feedback(models.Model):
    request_type = models.CharField(
        "Тип обращения",
        choices=RequestType.choices,
    )

    theme = models.CharField("Тема обращения", blank=True)
    full_text = models.TextField("Текст обращения")
    file = models.FileField("Файл", upload_to="feedback/", blank=True, null=True)
    date = models.DateTimeField("Дата обращения", auto_now_add=True)

    def __str__(self):
        return f"{self.request_type}:\n{self.full_text[:100]}"

    class Meta:
        verbose_name = "Обращение"
        verbose_name_plural = "Обращения"
        ordering = ["-date"]

service_portal/feedback/forms.py
from .models import Feedback
from django.forms import ModelForm, TextInput, Textarea, FileInput, Select
from django.core.exceptions import ValidationError


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ["request_type", "theme", "full_text", "file"]
        widgets = {
            "request_type": Select(
                attrs={
                    "class": "form-control",
                    "placeholder": "Тип обращения",
                }
            ),
            "theme": TextInput(
                attrs={"class": "form-control",
                       "placeholder": "Тема обращения", }
            ),
            "full_text": Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Текст обращения",
                }
            ),
            "file": FileInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }

    def clean_file(self):
        uploaded = self.cleaned_data.get("file")
        if uploaded:
            if uploaded.size > 10 * 1024 * 1024:
                raise ValidationError("Размер файла не должен превышать 10 Мб")
        return uploaded

service_portal/feedback/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView

from .forms import FeedbackForm
from .models import Feedback


def feedback_list(request):
    feedbacks = Feedback.objects.all()
    return render(request, "feedback/list.html", {"feedbacks": feedbacks})


def feedback_new_post(request):
    error = ""
    if request.method == "POST":
        form = FeedbackForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("feedback_list")
        else:
            error = "Форма заполнена некорректно"
    form = FeedbackForm()
    data = {"form": form, "error": error}

    return render(request, "feedback/new_post.html", data)


class FeedbackDetailView(DetailView):
    model = Feedback
    template_name = "feedback/detail_view.html"
    context_object_name = "feedback"

service_portal/feedback/templates/feedback/detail_view.html
{% extends 'feedback/layout.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ feedback.get_request_type_display }}: {{ feedback.theme }}</h1>
        <p>{{ feedback.full_text }}</p>
        {% if feedback.file %}
            <p>
                <a href="{{ feedback.file.url }}" download class="btn btn-primary">Скачать вложение</a>
            </p>
        {% else %}
            <p>
                Файлы не приложены
            </p>
        {% endif %}
    </div>
{% endblock %}

service_portal/feedback/templates/feedback/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'feedback/css/feedback.css' %}">
    <title>{% block titile %} {% endblock %}</title>
</head>
<body>
    <aside>
        <span class="logo">FeedBackSite</span>
        <h3>Навигация</h3>
        <ul>
            <li><a href="{% url 'feedback_list' %}"><i class="fas fa-house"></i> Список обращений</a></li>
            <li><a href="{% url 'feedback_new_post' %}"><button class="btn btn-info"><i class="fas fa-plus-circle"></i> Новое обращение</button></a></li>
        </ul>
    </aside>


    <main>
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

service_portal/feedback/templates/feedback/list.html
{% extends 'feedback/layout.html' %}

{% block title %}Список обращений{% endblock %}

{% block content %}
    <div class="features">
        <h1>Список поступивших обращений</h1>
        {% if feedbacks %}
            {% for fb in feedbacks %}
                <div class="alert alert-warning">
                    <h4>&bull;  {{ fb.get_request_type_display }}</h4>
                    <h3>«{{ fb.theme }}»</h3>
                    <p>{{ fb.full_text|truncatechars:90 }}</p>
                    <a href="{% url 'feedback_detail' fb.id %}" class="btn btn-warning">Подробнее</a>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-danger">
                <h3>Нет обращений</h3>
            </div>
        {% endif %}
    </div>
{% endblock %}

service_portal/feedback/templates/feedback/new_post.html
{% extends 'feedback/layout.html' %}

{% block title %}Новое обращение{% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма обращения</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.request_type }}<br>
            {{ form.theme }}<br>
            {{ form.full_text }}<br>
            {{ form.file }}<br>
            <span>{{ error }}</span>

            <button class="btn btn-success" type="submit">Добавить обращение</button>
        </form>
    </div>
{% endblock %}